### ISSUE TITLE
Missing signal.reg

### ISSUE THREAD

**Issue by arrissing** [hazelfazel/tuersteher#1]
Hi 

I attempted to install but the installer refers to a file called signal.reg, I could not find this file in the repository though.

am i doing something wrong?

**Comment by hazelfazel** [comment]
Thanks for the report. Fixed it, file is now online.

**Comment by arrissing** [comment]
Awesome, have a couple of hungry VM ready to test :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hazelfazel** [comment]
Hope, your VMs enjoyed the meal ;-)

Btw changed tuersteher.ini. Had to fix White- and Blacklist to Allow- and Blocklist.

**Comment by arrissing** [comment]
Hi Again 😊

 

Still having some issues, looks like it all goes in ok, but getting an error when activating driver.

 

The Tuersteher service failed to start due to the following error: 

The parameter is incorrect.

 

Any idea?

**Comment by hazelfazel** [comment]
Looks like an issue with github. They convert tuersteher.ini into an UTF-8 file. Tuersteher.ini must be in UTF-16 LE mode!!!
So ensure to save tuersteher.ini in UTF-16 LE mode (option in notepad under save as). Also ensure to end the tuersteher.ini with
[EOF]

# followed by a blank line. See example in zip file
[Tuersteher.zip](https://github.com/hazelfazel/tuersteher/files/6613426/Tuersteher.zip)
