### ISSUE TITLE
hashblocklist?

### ISSUE THREAD

**Issue by e-ggo** [hazelfazel/tuersteher#2]
Hi HazelFazel
This drive is really great
Can add a hashblocklist ??

**Comment by hazelfazel** [comment]
Hi e-ggo,
Sure you can block any executable by its sha256 hash.
Just enable the hash checking feature by setting
          [SHA256]
at the top configuration. Then go to the [BLOCKLIST] section and add the executable's sha256 hash value.
Cheers, HazelFazel

**Comment by e-ggo** [comment]
Hi HazelFazel
Thank you.
. Exe random name process releases from time to time, such as:
9e8d9-cb-7a-9e9-2635c320762.tmp
e8dfd9-cb33-447a-96e9-2635c32.tmp-wal
6bfbfc63-17ef-485e-bf55-35ee3f3aaef7.tmp-shm
Can Exe use the following rules without blocking the normal operation of EXE
*Exe>*.tmp-wal
*Exe>*.tmp-shm
*Exe>*.tmp
?
Thanks

**Comment by hazelfazel** [comment]
Türsteher recognises the star * for any number of characters and the question mark ? for exactly one character. So yes, you can define such rules. For example:

C:\Some_Path\Some_Executable.exe>C:\Users\Testuser\Temp\?????-??-??-???-???????????.tmp

Or

C:\Some_Path\Some_Executable.exe>C:\Users\Testuser\Temp\*-*-*-*-*.tmp

**Comment by hazelfazel** [comment]
See my description, there are some examples.
